"""full_migration_v2

Revision ID: 110c14e0f844
Revises: 
Create Date: 2026-05-08 09:07:44.761328

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '110c14e0f844'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_answers_id'), 'audio_answers', ['id'], unique=False)
    op.create_index(op.f('ix_audio_answers_user_id'), 'audio_answers', ['user_id'], unique=False)
    op.create_table('audio_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('lesson_id', sa.String(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('voice', sa.String(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_files_id'), 'audio_files', ['id'], unique=False)
    op.create_index(op.f('ix_audio_files_user_id'), 'audio_files', ['user_id'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('dialog_id', sa.Integer(), nullable=True),
    sa.Column('is_correction', sa.Integer(), nullable=True),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.create_table('contact_us',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_us_id'), 'contact_us', ['id'], unique=False)
    op.create_index(op.f('ix_contact_us_user_id'), 'contact_us', ['user_id'], unique=False)
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('training_type', sa.String(), nullable=False),
    sa.Column('word_type', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_category'), 'content', ['category'], unique=False)
    op.create_index(op.f('ix_content_id'), 'content', ['id'], unique=False)
    op.create_table('dialogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogs_id'), 'dialogs', ['id'], unique=False)
    op.create_index(op.f('ix_dialogs_theme'), 'dialogs', ['theme'], unique=False)
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_id'), 'faq', ['id'], unique=False)
    op.create_table('lesson_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Integer(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_answers_id'), 'lesson_answers', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_answers_lesson_id'), 'lesson_answers', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_answers_user_id'), 'lesson_answers', ['user_id'], unique=False)
    op.create_table('lesson_app_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_app_answers_id'), 'lesson_app_answers', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_app_answers_user_id'), 'lesson_app_answers', ['user_id'], unique=False)
    op.create_table('lesson_app_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('viewed', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.Column('last_activity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_app_progress_id'), 'lesson_app_progress', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_app_progress_lesson_id'), 'lesson_app_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_app_progress_user_id'), 'lesson_app_progress', ['user_id'], unique=False)
    op.create_table('lesson_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson', sa.String(), nullable=False),
    sa.Column('sub_topic', sa.String(), nullable=False),
    sa.Column('grammar_topic', sa.String(), nullable=True),
    sa.Column('word_number', sa.String(), nullable=True),
    sa.Column('vocabulary_word', sa.String(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('conversation_question', sa.Text(), nullable=True),
    sa.Column('conversation_affirmative', sa.Text(), nullable=True),
    sa.Column('conversation_interrogative', sa.Text(), nullable=True),
    sa.Column('conversation_yes', sa.Text(), nullable=True),
    sa.Column('conversation_no', sa.Text(), nullable=True),
    sa.Column('grammar_explanation', sa.Text(), nullable=True),
    sa.Column('exercise_type', sa.String(), nullable=True),
    sa.Column('exercise_answers', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_items_id'), 'lesson_items', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_items_lesson'), 'lesson_items', ['lesson'], unique=False)
    op.create_index(op.f('ix_lesson_items_sub_topic'), 'lesson_items', ['sub_topic'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('incorrect_count', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('last_activity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_progress_id'), 'lesson_progress', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_lesson_id'), 'lesson_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_user_id'), 'lesson_progress', ['user_id'], unique=False)
    op.create_table('otp_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('otp_code', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_store_id'), 'otp_store', ['id'], unique=False)
    op.create_index(op.f('ix_otp_store_identifier'), 'otp_store', ['identifier'], unique=False)
    op.create_table('privacy_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_privacy_policy_id'), 'privacy_policy', ['id'], unique=False)
    op.create_table('question_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('revealed', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_attempts_id'), 'question_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_question_attempts_user_id'), 'question_attempts', ['user_id'], unique=False)
    op.create_table('quiz_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_topic', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('db_mode', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('skipped', sa.Integer(), nullable=True),
    sa.Column('offset', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_history_id'), 'quiz_history', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_history_user_id'), 'quiz_history', ['user_id'], unique=False)
    op.create_table('sentence_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('original', sa.Text(), nullable=True),
    sa.Column('corrected', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('chat_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentence_corrections_id'), 'sentence_corrections', ['id'], unique=False)
    op.create_index(op.f('ix_sentence_corrections_user_id'), 'sentence_corrections', ['user_id'], unique=False)
    op.create_table('user_dialog_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('current_line', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_dialog_progress_id'), 'user_dialog_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_dialog_progress_user_id'), 'user_dialog_progress', ['user_id'], unique=False)
    op.create_table('user_learning_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('known_words', sa.Text(), nullable=True),
    sa.Column('words_to_review', sa.Text(), nullable=True),
    sa.Column('last_lesson_topic', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_learning_state_id'), 'user_learning_state', ['id'], unique=False)
    op.create_index(op.f('ix_user_learning_state_user_id'), 'user_learning_state', ['user_id'], unique=True)
    op.create_table('user_level_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('assessment_score', sa.Float(), nullable=True),
    sa.Column('vocabulary_score', sa.Float(), nullable=True),
    sa.Column('grammar_score', sa.Float(), nullable=True),
    sa.Column('fluency_score', sa.Float(), nullable=True),
    sa.Column('level_assigned', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_level_assessments_id'), 'user_level_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_user_level_assessments_user_id'), 'user_level_assessments', ['user_id'], unique=False)
    op.create_table('user_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('notification_type', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notifications_id'), 'user_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('daily_goal_minutes', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('viewed', sa.Boolean(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_progress_item_id'), 'user_progress', ['item_id'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_table('user_quiz_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('q1_name', sa.String(), nullable=True),
    sa.Column('q2_age', sa.String(), nullable=True),
    sa.Column('q3_occupation', sa.String(), nullable=True),
    sa.Column('q4_learning_goal', sa.Text(), nullable=True),
    sa.Column('q5_current_level', sa.String(), nullable=True),
    sa.Column('q6_study_frequency', sa.String(), nullable=True),
    sa.Column('q7_preferred_topics', sa.Text(), nullable=True),
    sa.Column('q8_learning_style', sa.String(), nullable=True),
    sa.Column('q9_challenges', sa.Text(), nullable=True),
    sa.Column('q10_previous_experience', sa.String(), nullable=True),
    sa.Column('q11_daily_time', sa.String(), nullable=True),
    sa.Column('q12_motivation', sa.Text(), nullable=True),
    sa.Column('q13_pronunciation_focus', sa.String(), nullable=True),
    sa.Column('q14_additional_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_quiz_data_id'), 'user_quiz_data', ['id'], unique=False)
    op.create_index(op.f('ix_user_quiz_data_user_id'), 'user_quiz_data', ['user_id'], unique=True)
    op.create_table('user_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('rapport_score', sa.Float(), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=True),
    sa.Column('last_interaction', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_relationship_id'), 'user_relationship', ['id'], unique=False)
    op.create_index(op.f('ix_user_relationship_user_id'), 'user_relationship', ['user_id'], unique=True)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('expiry_date', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('fcm_token', sa.String(), nullable=True),
    sa.Column('social_provider', sa.String(), nullable=True),
    sa.Column('social_id', sa.String(), nullable=True),
    sa.Column('mother_language', sa.String(), nullable=True),
    sa.Column('learning_level', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('next_notification', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('otp_code', sa.String(), nullable=True),
    sa.Column('otp_expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_user_relationship_user_id'), table_name='user_relationship')
    op.drop_index(op.f('ix_user_relationship_id'), table_name='user_relationship')
    op.drop_table('user_relationship')
    op.drop_index(op.f('ix_user_quiz_data_user_id'), table_name='user_quiz_data')
    op.drop_index(op.f('ix_user_quiz_data_id'), table_name='user_quiz_data')
    op.drop_table('user_quiz_data')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_item_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_id'), table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index(op.f('ix_user_level_assessments_user_id'), table_name='user_level_assessments')
    op.drop_index(op.f('ix_user_level_assessments_id'), table_name='user_level_assessments')
    op.drop_table('user_level_assessments')
    op.drop_index(op.f('ix_user_learning_state_user_id'), table_name='user_learning_state')
    op.drop_index(op.f('ix_user_learning_state_id'), table_name='user_learning_state')
    op.drop_table('user_learning_state')
    op.drop_index(op.f('ix_user_dialog_progress_user_id'), table_name='user_dialog_progress')
    op.drop_index(op.f('ix_user_dialog_progress_id'), table_name='user_dialog_progress')
    op.drop_table('user_dialog_progress')
    op.drop_index(op.f('ix_sentence_corrections_user_id'), table_name='sentence_corrections')
    op.drop_index(op.f('ix_sentence_corrections_id'), table_name='sentence_corrections')
    op.drop_table('sentence_corrections')
    op.drop_index(op.f('ix_quiz_history_user_id'), table_name='quiz_history')
    op.drop_index(op.f('ix_quiz_history_id'), table_name='quiz_history')
    op.drop_table('quiz_history')
    op.drop_index(op.f('ix_question_attempts_user_id'), table_name='question_attempts')
    op.drop_index(op.f('ix_question_attempts_id'), table_name='question_attempts')
    op.drop_table('question_attempts')
    op.drop_index(op.f('ix_privacy_policy_id'), table_name='privacy_policy')
    op.drop_table('privacy_policy')
    op.drop_index(op.f('ix_otp_store_identifier'), table_name='otp_store')
    op.drop_index(op.f('ix_otp_store_id'), table_name='otp_store')
    op.drop_table('otp_store')
    op.drop_index(op.f('ix_lesson_progress_user_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_lesson_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_id'), table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index(op.f('ix_lesson_items_sub_topic'), table_name='lesson_items')
    op.drop_index(op.f('ix_lesson_items_lesson'), table_name='lesson_items')
    op.drop_index(op.f('ix_lesson_items_id'), table_name='lesson_items')
    op.drop_table('lesson_items')
    op.drop_index(op.f('ix_lesson_app_progress_user_id'), table_name='lesson_app_progress')
    op.drop_index(op.f('ix_lesson_app_progress_lesson_id'), table_name='lesson_app_progress')
    op.drop_index(op.f('ix_lesson_app_progress_id'), table_name='lesson_app_progress')
    op.drop_table('lesson_app_progress')
    op.drop_index(op.f('ix_lesson_app_answers_user_id'), table_name='lesson_app_answers')
    op.drop_index(op.f('ix_lesson_app_answers_id'), table_name='lesson_app_answers')
    op.drop_table('lesson_app_answers')
    op.drop_index(op.f('ix_lesson_answers_user_id'), table_name='lesson_answers')
    op.drop_index(op.f('ix_lesson_answers_lesson_id'), table_name='lesson_answers')
    op.drop_index(op.f('ix_lesson_answers_id'), table_name='lesson_answers')
    op.drop_table('lesson_answers')
    op.drop_index(op.f('ix_faq_id'), table_name='faq')
    op.drop_table('faq')
    op.drop_index(op.f('ix_dialogs_theme'), table_name='dialogs')
    op.drop_index(op.f('ix_dialogs_id'), table_name='dialogs')
    op.drop_table('dialogs')
    op.drop_index(op.f('ix_content_id'), table_name='content')
    op.drop_index(op.f('ix_content_category'), table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_contact_us_user_id'), table_name='contact_us')
    op.drop_index(op.f('ix_contact_us_id'), table_name='contact_us')
    op.drop_table('contact_us')
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_audio_files_user_id'), table_name='audio_files')
    op.drop_index(op.f('ix_audio_files_id'), table_name='audio_files')
    op.drop_table('audio_files')
    op.drop_index(op.f('ix_audio_answers_user_id'), table_name='audio_answers')
    op.drop_index(op.f('ix_audio_answers_id'), table_name='audio_answers')
    op.drop_table('audio_answers')
    # ### end Alembic commands ###