"""Initial migration

Revision ID: 1777dd3e6599
Revises: 
Create Date: 2026-05-07 07:31:30.261651

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1777dd3e6599'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###